### PR TITLE
Subaccounts

### PR DESCRIPTION
**Pull request by KipsangEmmanuel**

### CODE REVIEW

**Review by kerenketepela — COMMENTED** [review]
This endpoint is done

**Review by kerenketepela — CHANGES_REQUESTED** [review]
Remove spacing on file naming

**Review by kerenketepela — CHANGES_REQUESTED** [review]
All routes objects should be in camel case i.e rename this `InitiateBulkCharge` to `initiateBulkCharge`

**Review by kerenketepela — CHANGES_REQUESTED** [review]
use camel case on route objects

**Comment by emmqnuelkipsqng** [comment]
okay

**Comment by ezkemboi** [comment]
Afer all rebase no changes here, closing this one.

**Pull request closed without merging**
