### PR TITLE
feature(start): set up endpoint for irecord

### PR DESCRIPTION
**Pull request by ezkemboi**

### CODE REVIEW

**Review by emmqnuelkipsqng — APPROVED** [review]

**Review by chepkok3 — COMMENTED** [review]
This is looking good. We are making good progress, keep it up!

**Comment by ezkemboi** [comment]
Yes, there is much progress

**Comment by Kipngetich98** [comment]
Good work guys.soon the project will be flowing when this foundation is done.

**Comment by ezkemboi** [comment]
That is very sure, I am working on laying a good foundation for the same.

**Comment by Nicholas-Kipkoech** [comment]
when all this is done we will ensure that the **code** is clean and well **documented**

**Comment by ezkemboi** [comment]
Sure sure, w will need to make sure we make use of that.

**Pull request merged**
