### PR TITLE
feature(resources): add transaction splits and customers

### PR DESCRIPTION
**Pull request by ezkemboi**

### CODE REVIEW

**Review by Nicholas-Kipkoech — APPROVED** [review]
Good stuffs

**Review by Kipngetich98 — APPROVED** [review]

**Review by koechcoding — COMMENTED** [review]
riding along

**Comment by chepkok3** [comment]
Great additions!

**Comment by Cheberi** [comment]
Great stuff

**Comment by ezkemboi** [comment]
Kusukuma kabisa, it will be great.

**Pull request merged**
